version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'monthly'
      day: 'sunday'
      time: '19:00'
      timezone: 'Europe/Berlin'
    commit-message:
      prefix: 'deps'
    groups:
      fortawesome:
        patterns:
          - '@fortawesome/*'
