name: Beta Deploy

on:
  push:
    branches:
      - main

jobs:
  trigger-dev-server:
    name: Restart Development Server for Rebuilding
    needs: upload-to-server
    runs-on: ubuntu-latest
    steps:
      - name: Send Restart
        uses: outsparkled/pterodactyl-power-action@v0.1.0
        with:
          panel-url: ${{ secrets.PANEL_URL }}
          server-id: ${{ secrets.PANEL_DEV_SERVER_ID }}
          bearer-token: ${{ secrets.PANEL_BEARER_TOKEN }}
          power-action: 'restart'
