name: Test PR

on:
  - pull_request

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: yarn install

      - name: Build Svelte app
        run: yarn build
        env:
          MINIO_ENDPOINT: dummy
          MINIO_PORT: dummy
          MINIO_ACCESS_KEY: dummy
          MINIO_SECRET_KEY: dummy
          MINIO_BUCKET: dummy
