name: Test PR

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      DISCORD_BOT_TOKEN: '1234567890'
      DISCORD_TEAM_ROLE_ID: '706087016613281842'
      DISCORD_CUBYX_GUILD: '665917454626717746'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install bun for faster builds
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: npm ci

      - name: Build Svelte app
        run: bun run build

      - name: Test Svelte app
        run: bun run test

  eslint:
    name: Check & ESLint
    runs-on: ubuntu-latest
    env:
      DISCORD_BOT_TOKEN: '1234567890'
      DISCORD_TEAM_ROLE_ID: '706087016613281842'
      DISCORD_CUBYX_GUILD: '665917454626717746'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install bun for faster builds
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: npm ci

      - name: Svelte Check
        run: bun run check

      - name: Run ESLint
        run: bun run lint
