name: Deploy SvelteKit App

on:
  release:
    types:
      - published

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      DISCORD_BOT_TOKEN: '1234567890'
      DISCORD_TEAM_ROLE_ID: '706087016613281842'
      DISCORD_CUBYX_GUILD: '665917454626717746'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build SvelteKit app
        run: npm run build

      - name: Set Up SSH
        run: |
          mkdir -p ~/.ssh
          # Create a config file for SSH
          echo -e "Host custom-ssh\n  HostName ${{ secrets.DEPLOY_HOST }}\n  Port ${{ secrets.DEPLOY_PORT }}\n  User ${{ secrets.DEPLOY_USERNAME }}.${{ secrets.DEPLOY_SERVER_ID }}\n  PasswordAuthentication yes" > ~/.ssh/config
        env:
          SSH_PASSWORD: ${{ secrets.DEPLOY_PASSWORD }}

      - name: Sync with Production Server
        run: |
          rsync -avz --delete ./build/ custom-ssh:/
          rsync -avz --delete package.json package-lock.json custom-ssh:/
          rsync -avz --delete prisma/ custom-ssh:/
        env:
          SSH_PASSWORD: ${{ secrets.DEPLOY_PASSWORD }}

      - name: Send Restart
        uses: outsparkled/pterodactyl-power-action@v0.1.0
        with:
          panel-url: ${{ secrets.PANEL_URL }}
          server-id: ${{ secrets.DEPLOY_SERVER_ID }}
          bearer-token: ${{ secrets.PANEL_BEARER_TOKEN }}
          power-action: 'restart'
